baseURL = "https://universemul.github.io/blog"
locale = "fr"
title = "David Barthelemy"
theme = "typo"
enableRobotsTXT = true

[taxonomies]
tag = 'tags'

[params]
description = "david barthelemy"

theme = 'dark'
colorPalette = 'default'
hideHeader = false

homeIntroTitle = 'Hello!'
homeIntroContent = "Entre écriture de code, écriture d'histoires et astrophotographie, ce blog est mon espace d'expérimentation. J'y partage mes projets [dev](/blog/dev) (notamment mon application [Welshie](https://www.welshie.fr/)), mon parcours créatif entre [écrits](/blog/writing) et [lectures](/blog/read), ainsi que mes captures du ciel en [photo](/blog/photo)."

singleDateFormat = '2 Jan 2006'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '02 Jan 2006'

# Footer
showFooter = false

[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "~"

[[params.social]]
name = "github"
url = "https://github.com/Universemul"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/davidbarthelemy28/"

[[params.menu]]
  name = "Home"
  url = "/blog"
[[params.menu]]
  name = "Ecriture"
  url = "/blog/writing/"
[[params.menu]]
  name = "Dev"
  url = "/blog/dev"
[[params.menu]]
  name = "Lecture"
  url = "/blog/read"
[[params.menu]]
  name = "Photo"
  url = "/blog/photo"
[[params.menu]]
  name = ".rss"
  url = "/blog/index.xml"
  newTab = true

[markup]
[markup.highlight]
style = 'bw'

